### ISSUE TITLE
Check BoxPrimitive builder

### ISSUE THREAD

**Issue by LeandroJavierLaino** [tgc-utn/tgc-monogame-samples#15]
Por alguna razón cuando se crea un set de Boxes quedan pegadas como un único mesh.

**Comment by rejurime** [comment]
Me da mas info mi amigo? bajo que contexto pasaba esto?

**Comment by LeandroJavierLaino** [comment]
era cuando quería armar más de una caja a la vez, ponía un for de 0 a 9 por ej para que arme las cajas, en el apartado físico si hacía las 10 cajas pero en el gráfico por alguna razón me armaba 10 cajas en la disposición del loop (si hacia una pirámide eran 10 piramides de 10 cajas, si eran columnas eran 10 columnas de 10 cajas) y esos set de cajas quedaban cada una asociadas a una de las cajas físicas. 

Esto solo me paso usando la primitiva de la caja porque cuando use models o esferas (por esto quedaron nombres de variables de esferas seguramente) funcionaba bien, es decir, si tenía 10 TGCcitos me asociaba a cada uno a una caja.
