### ISSUE TITLE
Mejorar la creacion de los modifiers

### ISSUE THREAD

**Issue by rejurime** [tgc-utn/tgc-monogame-samples#47]
* Estamos bien con la forma que se crean los modifiers? es para discutir pros y contras de diferentes enfoques.

**Comment by AVinitzca** [comment]
DragFile es un Draft de una funcionalidad que es medio compleja. Podemos seleccionar archivos pero cargarlos dinámicamente no es fácil por el Content.

**Comment by rejurime** [comment]
Si, lo vi, no se usa pero como habia bastante avanzado preferi sumarla y dejar aca esto, pero si qeures hago split de issue.
